## Numpy Introduction

In [1]:
import numpy as np

In [3]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [4]:
a.shape

(6,)

In [18]:
type(a)

numpy.ndarray

In [16]:
a.dtype

dtype('int64')

In [ ]:
# To convert into 2-D array
a2=a[np.newaxis,:]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [ ]:
# To convert into 3-D array
a3=a2[np.newaxis,:]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

### Creating array with Numpy

In [9]:
a=np.array([1,2,3,4,5,6,7])
b=np.array([(1,2,3,4,5,6,7),(4,5,6,7,8,9,10)])

In [7]:
a.shape

(6,)

In [11]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

### Initialize arrays

In [ ]:
zeros=np.zeros((3,4)) #(rows,columns)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [14]:
# Full Array
full=np.full((2,5),5)
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [15]:
# Identity Matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Array attributes

In [20]:
a.shape

(7,)

In [ ]:
len(a) # length of the array

7

In [ ]:
a.ndim # dimension of the array

1

In [23]:
b.ndim

2

In [ ]:
len(b) # gives length of elements

2

In [ ]:
b.size # gives number of elements

14

### Basic operations

In [ ]:
g=a-b # subtraction
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [27]:
g=b-a
g

array([[0, 0, 0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3, 3, 3]])

In [ ]:
h=a+b # addition
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [ ]:
h1=np.add(a,b) # another method of element-wise addition
h1

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [ ]:
i=a*b # multiplication
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [ ]:
k=a**2 # taking square
k

array([ 1,  4,  9, 16, 25, 36, 49])