## Numpy (Part-2)

In [1]:
import numpy as np

In [2]:
empty=np.empty((2,3))
print(empty)
print("------------")
print(empty[1])

[[-6.95322776e-310  2.88883869e+180  1.13827254e-311]
 [ 1.13827254e-311  4.94065646e-323  7.41098469e-323]]
------------
[1.13827254e-311 4.94065646e-323 7.41098469e-323]


In [3]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
even=np.arange(0,23,2) #even numbers from 0 to 22
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [5]:
odd=np.arange(1,23,2) # array of odd numbers from 1 to 23
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [6]:
# specific difference between numbers
diff=np.arange(0,23,5)
diff

array([ 0,  5, 10, 15, 20])

In [7]:
lin=np.linspace(0,10,num=5)
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
lin=np.linspace(0,10,num=10)
lin

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [9]:
lin=np.linspace(0,-10,num=10)
lin

array([  0.        ,  -1.11111111,  -2.22222222,  -3.33333333,
        -4.44444444,  -5.55555556,  -6.66666667,  -7.77777778,
        -8.88888889, -10.        ])

In [10]:
# define the dtype of an array
x=np.ones(3,dtype=np.float64)
x

array([1., 1., 1.])

In [11]:
# sorting an array
arr=np.array([2,4,3,6,7,9,5,1])
arr.sort()
arr

array([1, 2, 3, 4, 5, 6, 7, 9])

In [12]:
# Concatenation
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.concatenate((a,b))
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


### Concatenating 2-D arrays

In [13]:
x=([[1,2],[3,4]])
y=([[5,6]])
z=np.concatenate((x,y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# 3-D array
arr_3d = np.array([[[1, 2, 3], [4,
                                5, 6]], [[7, 8, 9], [10, 11,
                                                     12]]])
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [15]:
arr_3d.ndim

3

In [16]:
arr_3d.shape

(2, 2, 3)

In [17]:
# Create 3-D array of (3,1,4)
arr_3d = np.full((3, 1, 4), 5)
arr_3d

array([[[5, 5, 5, 5]],

       [[5, 5, 5, 5]],

       [[5, 5, 5, 5]]])

In [18]:
arr_3d.shape

(3, 1, 4)

In [19]:
len(arr_3d)

3

In [20]:
arr_3d.size

12

In [21]:
arr_3d.reshape(6,2)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [22]:
arr_3d.reshape(3,2,2)

array([[[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]]])

### Indexing & Slicing

In [23]:
a=np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
a[-4:]

array([5, 6, 7, 8])

In [25]:
a[-2:]

array([7, 8])

In [26]:
a[-1:]

array([8])

In [27]:
a[:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
a[5]

np.int64(6)

In [29]:
a[-4:-2]

array([5, 6])

In [30]:
# 2-D array
arr = [[1, 2, 3], [4, 5, 6],
       [7, 8, 9]]
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:
arr[0]

[1, 2, 3]

In [32]:
arr[2]

[7, 8, 9]

In [33]:
# 3-D array
b= np.array([[[1, 2, 3], [4,
                                5, 6]], [[7, 8, 9], [10, 11,
                                                     12]]])
print(b)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [34]:
b[1:,1:]

array([[[10, 11, 12]]])

In [35]:
b[b>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
b[b<8]

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
b[b%2==0] # to filter even numbers

array([ 2,  4,  6,  8, 10, 12])

In [38]:
b[b%2==1] # to filter odd numbers

array([ 1,  3,  5,  7,  9, 11])

In [39]:
# Use two conditions
b[(b>2)&(b<9)]

array([3, 4, 5, 6, 7, 8])

In [40]:
a=np.array(['1,2,3,4,5,6,'])
b=np.array(['5,6,7,8,9,10'])

In [43]:
d=np.hstack((a,b))
d

array(['1,2,3,4,5,6,', '5,6,7,8,9,10'], dtype='<U12')

---------


## Matrix or Matrices

In [48]:
b=np.arange(0,100,2).reshape(5,10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [52]:
c=b[0:3,3:6]
c

array([[ 6,  8, 10],
       [26, 28, 30],
       [46, 48, 50]])

In [55]:
b.max()


np.int64(98)

In [56]:
b.min()

np.int64(0)

In [57]:
b.sum()

np.int64(2450)

In [58]:
b.min(axis=0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
b.max(axis=0)

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [60]:
b.max(axis=1)

array([18, 38, 58, 78, 98])

In [62]:
m=np.arange(0,10,2)
m

array([0, 2, 4, 6, 8])